apiVersion: v1
kind: Service
metadata:
  name: dummy-apis
  labels:
    app: dummy-apis
spec:
  ports:
  - name: "dummy-apis"
    port: 4545
    protocol: TCP
    targetPort: 4545
  selector:
    app: dummy-apis
  type: LoadBalancer

